spring:
  application:
    name: oscms-course-service
  
server:
  port: 8082

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

---
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:mysql://localhost:3306/oscms_course_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:760810abcd..}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    
# MyBatis Plus Configuration
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.osc.oscms.courseservice.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:YourSuperSecretKeyForJWTGenerationWhichIsVeryLongAndSecure12345!}
  expiration:
    ms: ${JWT_EXPIRATION_MS:3600000} # 1 hour

# Logging
logging:
  level:
    com.osc.oscms.courseservice: DEBUG

---
spring:
  config:
    activate:
      on-profile: k8s
  application:
    name: oscms-course-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA Configuration for K8s
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
    
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Server Configuration for K8s
server:
  port: 8082

# Eureka Client Configuration for K8s
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    prefer-ip-address: true

# MyBatis Plus Configuration
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.osc.oscms.courseservice.domain
  configuration:
    map-underscore-to-camel-case: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:YourSuperSecretKeyForJWTGenerationWhichIsVeryLongAndSecure12345!}
  expiration:
    ms: ${JWT_EXPIRATION_MS:3600000}

# Logging
logging:
  level:
    com.osc.oscms.courseservice: INFO
