spring:
  application:
    name: oscms-course-service
  profiles:
    active: dev
  
server:
  port: 8082

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

---
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:mysql://localhost:3306/oscms_course_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:760810abcd..}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    
# MyBatis Plus Configuration
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.osc.oscms.courseservice.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:YourSuperSecretKeyForJWTGenerationWhichIsVeryLongAndSecure12345!}
  expiration:
    ms: ${JWT_EXPIRATION_MS:3600000} # 1 hour

# Logging
logging:
  level:
    com.osc.oscms.courseservice: DEBUG
