server:
  port: 8082 # <--- 为 course-service 分配新端口

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oscms_course_db # <--- 指向 course-service 的数据库
    username: root
    password: your_password # <--- 替换为您的数据库密码
  flyway:
    enabled: true
    baseline-on-migrate: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 将来为 Feign Client 配置 URL
# feign:
#  client:
#    config:
#      user-service:
#        url: http://localhost:8081 # user-service 的地址